version: '3'

services:
  django_concept_app:
    build: .
    container_name: django_concept_app
    # command: python3.8 manage.py runserver 0.0.0.0:8000
    # command: bash -c "python3.8 -m pip install django-debug-toolbar==4.1.0 && python3.8 manage.py runserver 0.0.0.0:8000"
    command: sh -c "python3.8 -m pip install django-debug-toolbar==4.1.0 && python3.8 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always
    networks:
    - Django_concept_app_network


networks:
  Django_concept_app_network:
    driver: bridge

  